export const IELTS_CORE_VOCABULARY_LABEL =
  "179 high-frequency IELTS listening/speaking words plus natural variants from the mother-topic notes";

export const IELTS_MOTHER_TOPICS = [
  "travel / coastline / outdoor nature",
  "public place / library / renovated building",
  "environment / technology / exhibition",
  "shopping / mall / discount",
  "person / occupation / professional help",
  "study / group project / difficult task",
  "documentary / online information / nature",
  "volunteer / charity / donation",
  "sport / health / challenge",
  "technology product / laptop / update",
  "country to visit / New Zealand-style travel plan",
  "food / hot pot / traditional meal"
];

export const IELTS_CORE_VOCABULARY = [
  "reserve",
  "in advance",
  "fee",
  "accommodation",
  "budget",
  "adjust",
  "coastline",
  "urban",
  "remote",
  "environment",
  "diversity",
  "vegetation",
  "habitat",
  "species",
  "emigrate",
  "allergic",
  "entertainment",
  "geology",
  "countryside",
  "outdoor",
  "transport",
  "transfer",
  "advantage",
  "disadvantage",
  "establish",
  "renovate",
  "refurbish",
  "structure",
  "reference materials",
  "extensive",
  "expertise",
  "approach",
  "motivate",
  "improve",
  "overlook",
  "omit",
  "opportunity",
  "prevent",
  "misunderstand",
  "feedback",
  "analysis",
  "result",
  "handle",
  "support",
  "ideal",
  "rigorous",
  "restrict",
  "statistics",
  "maximum",
  "minimum",
  "initial",
  "limited",
  "decrease",
  "lack",
  "update",
  "classify",
  "entrance",
  "behind",
  "below",
  "beside",
  "available",
  "trend",
  "risky",
  "poisonous",
  "warning",
  "protect",
  "injury",
  "tactics",
  "rely on",
  "space travel",
  "specific",
  "request",
  "organization",
  "produce",
  "administer",
  "occupation",
  "staff",
  "discount",
  "hospitality",
  "shape like",
  "depressed",
  "well-known",
  "specialize in",
  "typical",
  "uncommon",
  "accurately",
  "expand",
  "enhance",
  "power",
  "fuel",
  "disused",
  "donate",
  "visualize",
  "repetition",
  "poor",
  "durable",
  "pollutant",
  "continue",
  "sale",
  "cheap",
  "jewellery",
  "ring",
  "bracelet",
  "necklace",
  "luxurious",
  "artwork",
  "painting",
  "craft",
  "publicity",
  "marketing",
  "handy",
  "newest",
  "mate",
  "demonstrate",
  "dentist",
  "ability",
  "skill",
  "nurse",
  "straightforward",
  "trust",
  "health",
  "medical",
  "sickness",
  "illness",
  "fitness",
  "professional",
  "education",
  "purpose",
  "framework",
  "data",
  "amount of",
  "funding",
  "percentage",
  "deadline",
  "try hard",
  "movie",
  "documentary",
  "online",
  "website",
  "visual",
  "ancient",
  "mammal",
  "creature",
  "cliff",
  "fossil",
  "rock",
  "landscape",
  "graph",
  "chart",
  "expert",
  "charity",
  "ordinary people",
  "community",
  "category",
  "computer",
  "laptop",
  "demanding",
  "dangerous",
  "permanent",
  "temporary",
  "annual",
  "press",
  "steal",
  "military",
  "round",
  "order",
  "safe",
  "strength",
  "energy",
  "pressure",
  "goal",
  "physical",
  "mental",
  "effort",
  "achievement",
  "at present",
  "out of date",
  "capacity",
  "more than",
  "install",
  "modify",
  "repair",
  "economic",
  "waste",
  "international",
  "country",
  "wildlife",
  "tradition",
  "lifestyle",
  "affect",
  "food",
  "preference",
  "social activity",
  "every day",
  "occasionally"
];
